name: Deploy Azure Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create resource group if not exists
      run: |
        az group create --name rg-dev-myapp --location eastus

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        resourceGroupName: 'rg-dev-myapp'
        template: 'infra/templates/webAppTemplate.json'
        parameters: |
          location=germanywestcentral
          baseAppName=myapp
          environment=dev
